navigation bar tool
richarddushime/gdsc pull request #9
Opened 2021-10-20 23:45 UTC by Agabaderrickjunior

2021-10-20 23:46 UTC, Agabaderrickjunior commented
please accept this

2021-10-24 12:10 UTC, jnsereko commented
please  @Agabaderrickjunior 

1. squash your commits   https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits
2. add issue link 
3. add a short video / screen capture of your changes 

Thank for the work.

2021-10-24 12:14 UTC, jnsereko commented on .github/supportus.yml
> +patreon: # Replace with a single Patreon username
does this also satisfy https://github.com/richarddushime/gdsc/issues/7

2021-10-24 12:15 UTC, jnsereko commented on style.css
> +li a{
which element is this targeting?

2021-10-24 12:18 UTC, jnsereko requested changes

2021-10-24 12:18 UTC, jnsereko commented on new changes
> +    </ul>
```
<div class="nav">
    <ul>
        <li><a href="HOME">HOME</a></li>
        <li><a href="CONTACT US">CONTACT</a></li>
        <li><a href="ABOUT US">ABOUT US</a> </li>
        <li><a href="SIGN IN">SIGN IN</a></li>
    </ul>
</div>
```

2021-10-24 13:49 UTC, mherman22 requested changes
Your pull request is not descriptive enough. A little explanation of what your pull request does

2021-10-26 15:59 UTC, merged